apiVersion: apps/v1
kind: Deployment
metadata:
  name: statsd-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statsd-exporter
  template:
    metadata:
      labels:
        app: statsd-exporter
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: statsd-exporter
          image: satyak1238.azurecr.io/prom/statsd-exporter:latest
          ports:
            - containerPort: 9125
              name: port1
            - containerPort: 9102
              name: port2
---
apiVersion: v1
kind: Service
metadata:
  name: statsd-exporter
spec:
  #type: LoadBalancer
  ports:
    - port: 9125
      name: port1
    - port: 9102
      name: port2
  selector:
    app: statsd-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: prometheus
          image: satyak1238.azurecr.io/prom/prometheus:latest
          ports:
            - containerPort: 9090
              name: port1
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      #targetPort: 9090
      protocol: TCP
      name: port1
  selector:
    app: prometheus
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: grafana
          image: satyak1238.azurecr.io/grafana/grafana:latest
          ports:
            - containerPort: 3000
              name: port1
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: port1
  selector:
    app: grafana

